const authRoutes = require("./authRoute");
const bookRoutes = require("./bookRoute");
const adminRoutes = require("./adminRoute");
const userRoutes = require("./userRoute");
const categoryRoutes = require("./categoryRoute");
const feedbackRoutes = require("./feedbackRoute");
const orderRoutes = require("./orderRoute");
const ghnRoutes = require("./ghnRoute");
const paymentRoutes = require("./paymentRoute");
const blogRoutes = require("./blogRoute");
const commnetRoutes = require("./commnetRoute");
const quizRoutes = require("./quizRoute");
const mealSetRoutes = require("./mealSetRoute");
const foodRoutes = require("./foodRoute");
const blogCategoryRoutes = require("./blogCategoryRoute");
const routes = (app) => {
  app.use("/auth", authRoutes);
  app.use("/quiz", quizRoutes);
  app.use("/product", bookRoutes);
  app.use("/admin", adminRoutes);
  app.use("/mealset", mealSetRoutes);
  app.use("/user", userRoutes);
  app.use("/category", categoryRoutes);
  app.use("/feedback", feedbackRoutes);
  app.use("/order", orderRoutes);
  app.use("/ghn", ghnRoutes);
  app.use("/payment", paymentRoutes);
  app.use("/blog", blogRoutes);
  app.use("/comment", commnetRoutes);
  app.use("/food", foodRoutes);
  app.use("/blog-category", blogCategoryRoutes);
};

module.exports = routes;
